name: Docker Container

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Dock Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u anywaysbot --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anywaysopen/tilemaker:staging --tag anywaysopen/tilemaker:staging-0.$GITHUB_RUN_NUMBER
    - name: Push Docker image.
      run: docker push anywaysopen/tilemaker:staging
    - name: Push Docker image.
      run: docker push anywaysopen/tilemaker:staging-0.$GITHUB_RUN_NUMBER